### PR TITLE
Windows (MSVC) compatibility

### PR DESCRIPTION
**Pull request by InfRandomness**
This MR aims at making asyncpp compatible with the visual studio / msvc toolchain, as well as with the clang-cl toolchain

### CODE REVIEW

**Comment by InfRandomness** [comment]
@Thalhammer is it possible that [this test](https://github.com/Thalhammer/asyncpp/blob/master/test/promise.cpp#L144-L160) contains UB?
Whenever that test run, this error 
image
occurs
And after searching for a little while, I've mainly seen it come from UB
The only roadblock here is that I can not use ThreadSanitizer or UBSanitizer because : 
- MSVC does not have either of them (only AddressSanitizer)
- Clang-CL does not seem to support coroutine (therefore the project does not even compile)

**Comment by InfRandomness** [comment]
For now, all of the tests are seemingly passing with MSVC
However, I have quite some issues with clang-cl that fails to compile [this part of the code](https://github.com/Thalhammer/asyncpp/blob/master/include/asyncpp/task.h#L123) : 
image

**Comment by InfRandomness** [comment]
I propose that we keep clang-cl aside and proceed to merge the msvc support
clang-cl is way too buggy to compile this project properly, and I have a bad feeling that it will take a LONG time until it is good enough for the job.

**Comment by InfRandomness** [comment]
Should I revert that workaround if we keep clang-cl aside for the time being? Since that solves an issue msvc didn't have.

**Comment by Thalhammer** [comment]
> Should I revert that workaround if we keep clang-cl aside for the time being? Since that solves an issue msvc didn't have.

I guess theres no harm in keeping it given that its still technically the same code (just changed to make clang get it). So it shouldn't influence anything else. We will have to check the other libs (curl & grpc) for the same issue cause returning a awaiter object is a pretty common thing in coroutines and especially the grpc wrapper relies heavily on templates, so it likely has the same issue.

I don't know how commonly used clang-cl is on windows, is it worth supporting ? If so we could maybe put it in the "works, but expect bugs" category similar to early clang/gcc versions. I think as long as msvc compiles fine it's probably fine though.

**Comment by InfRandomness** [comment]
> I don't know how commonly used clang-cl is on windows, is it worth supporting ? If so we could maybe put it in the "works, but expect bugs" category similar to early clang/gcc versions. I think as long as msvc compiles fine it's probably fine though.

I am totally unsure if clang-cl is widely used, I would guess not, but I would personally very much rather use that to msvc

**Comment by Thalhammer** [comment]
> I am totally unsure if clang-cl is widely used, I would guess not, but I would personally very much rather use that to msvc

I mean theres also a windows version of clang and gcc, the only difference is that "normal" clang uses the same flags/cmd options as it does on linux (and afaik produces binaries that can't link with msvc, though that might have changed), while clang-cl emulates the command line options msvc's cl uses and tries to be as compatible with msvc as possible (hence the delayed template thing).
To be perfectly honest I've never heard of it prior to this pr, so I don't think its super common yet.

**Comment by InfRandomness** [comment]
> > I am totally unsure if clang-cl is widely used, I would guess not, but I would personally very much rather use that to msvc
> 
> I mean theres also a windows version of clang and gcc, the only difference is that "normal" clang uses the same flags/cmd options as it does on linux (and afaik produces binaries that can't link with msvc, though that might have changed), while clang-cl emulates the command line options msvc's cl uses and tries to be as compatible with msvc as possible (hence the delayed template thing). To be perfectly honest I've never heard of it prior to this pr, so I don't think its super common yet.

I'm almost definitely sure the bugs I have on clang-cl will happen too on clang, I think it's just a different driver but with the same clang behind it

**Comment by Thalhammer** [comment]
> Edit: It indeed produces the same errors....

AFAIK: It should only produce the errors on normal clang if you enable delayed templates, which noone does on Linux cause it's not how it specified in the standard and has never been a thing on Linux unlike in msvc.

**Comment by InfRandomness** [comment]
I'm not sure why this is occurring : https://github.com/Thalhammer/asyncpp/runs/8287717622?check_suite_focus=true

The used cmake version (in the ci) seems to be 3.12.x, but this feature appeared in 3.11, so this should all work?

**Comment by InfRandomness** [comment]
>  If so we could maybe put it in the "works, but expect bugs" category similar to early clang/gcc versions. I think as long as msvc compiles fine it's probably fine though.

I think it would be best to only support msvc at the moment, since clang-cl support will take a while, and yeah, as you mentionned, it's not really important since not a whole lot of people seem to be using it

**Comment by InfRandomness** [comment]
(Oops, didn't mean to do that)

**Comment by Thalhammer** [comment]
> The used cmake version (in the ci) seems to be 3.12.x, but this feature appeared in 3.11, so this should all work?

FetchContent is a 3.11 feature, the specific function FetchContent_MakeAvailable is only introduced in 3.14.

Thats fine, you can just raise the min version, all the other projects use 3.15 anyway cause I use FetchContent there to load this one if its not already available.

**Comment by InfRandomness** [comment]
> > The used cmake version (in the ci) seems to be 3.12.x, but this feature appeared in 3.11, so this should all work?
> 
> FetchContent is a 3.11 feature, the specific function FetchContent_MakeAvailable is only introduced in 3.14.
> 
> Thats fine, you can just raise the min version, all the other projects use 3.15 anyway cause I use FetchContent there to load this one if its not already available.

[Like so?](https://github.com/Thalhammer/asyncpp/pull/5/commits/68fb8b00be6a9a0e1ec6bff3532f85ba96bc99c9)

**Comment by Thalhammer** [comment]
> [Like so?](https://github.com/Thalhammer/asyncpp/pull/5/commits/68fb8b00be6a9a0e1ec6bff3532f85ba96bc99c9)

Yes and the first line of CMakeLists.txt also needs a change.

**Comment by InfRandomness** [comment]
All the tests seem to be passing, is this ready to merge?

**Comment by InfRandomness** [comment]
well, so, I considered adding windows CI in that PR, but I realized that would be a lot of work so I thought "why not make it in another PR"
but, it's your call
(and also I'm very bad at devops, and devops annoys me, sort of)

**Comment by Thalhammer** [comment]
> why not make it in another PR

Sounds good to me.

> and also I'm very bad at devops, and devops annoys me, sort of

It doesn't need to be perfect 🙂

**Pull request merged**
